Added the Pleistocene version of the CPT-Vs correlation from Andrus et al. (2007)
ucgmsim/Vs30 pull request #38
Opened 2024-11-29 03:13 UTC by AndrewRidden-Harper

Jaehwi found that the Pleistocene version of the CPT-Vs correlation from Andrus et al. (2007) performs the best but it wasn't available in vs_calc. I added the Pleistocene version, and also noticed a version for "tertiary age cooper marl" so I added that as well. I also added the Andrus et al. (2007) reference paper to the repo, with the idea that all reference papers with correlations used in vs_calc could also be added in the future.

2024-12-02 00:20 UTC, lispandfound requested changes
Just formatting changes here.

2024-12-02 00:20 UTC, lispandfound commented on VsViewer/vs_calc/cpt_vs_correlations.py
> +    qt in kPa.
Could you run copilot over this file and get it to produce numpy-style docstrings for the functions in this module?

2024-12-02 00:20 UTC, lispandfound commented on VsViewer/vs_calc/cpt_vs_correlations.py
> +        [13.0 * ((cpt.qt * 1000) ** 0.382) * (cpt.depth**0.099)]
The formatting here is not good, could you also run ruff over the file to correct the formatting?

2024-12-02 21:15 UTC, joelridden approved these changes
Nice, formatting would be nice, eventually should get ruff etc for this repo to tidy this all up

2024-12-04 23:11 UTC, lispandfound approved these changes
approve on the proviso of ruff formatting the repo

2024-12-04 23:11 UTC, merged